spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olx-user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  zipkin:
    base-url: http://localhost:9411